### ISSUE TITLE
Previous/next image shortcuts not working with classification labels

### ISSUE THREAD

**Issue by ma0ho** [ChristianMarzahl/Exact#29] opened 2021-02-24 16:10 UTC
When using classification labels, the previous/next frame shortcuts ((e) and (q)) are not working after one of the label checkboxes have been clicked.

OS: Windows
Browser: Firefox 85.0.2

**Comment by ChristianMarzahl** [comment] 2021-02-25 07:04
Moin,

I was unable to reproduce this behaviour. Can please test if it is a focus bug by setting the focus to a different object and press (e) or (q) again? 

Thank you for reporting.

With kind regards,
Christian

**Comment by ma0ho** [comment] 2021-02-25 08:11
Yes, this seems to be a focus bug. It only happens, if you click a checkbox and it is resolved by subsequently clicking anywhere else.

**Comment by ChristianMarzahl** [comment] 2021-03-12 16:38
Fixed in 
https://github.com/ChristianMarzahl/Exact/commit/68d870ea06912c992c69e376b346aa6ce32a1a33

**Closed by ChristianMarzahl** 2021-03-12 16:38 UTC
